site_name: Teaching Literature Club

repo_url: https://github.com/NBISweden/teaching_literature_club

nav:
  - About:
      - About us: README.md
  - Past events:
      - Past events: past_events.md
  - FAQ:
      - Frequently asked questions: faq.md
  - Misc:
      - Data: data.md
      - Code of conduct: code_of_conduct.md
      - Contributing: contributing.md
      - Reflections: reflections.md

theme:
  name: material
  greetings: Welcome to the Teaching Literature Club
  font:
    text: Lato
    code: JetBrains Mono
  palette:
    primary: white

  logo: logo/nbis_logo.png

  features:
    - toc.integrate
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.path
    - navigation.footer
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.action.edit
    - content.action.view

markdown_extensions:
  - toc:
      toc_depth: 2
      permalink: true
      permalink_title: Anchor link to this section for reference
  - admonition
  - tables
  - attr_list
  - footnotes
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.keys
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
